version: '3.4'

services:
  postgres:
    image: postgres:18
    container_name: threads-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: threads
      POSTGRES_DB: threads
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: